services: 
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.18-openssl
    restart: always
    ports:
      - 1883:1883
    networks:
      - iot
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  telegraf:
    container_name: telegraf
    image: telegraf:1.18
    restart: always
    networks:
      - iot
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on: 
      - influxdb

  influxdb:
    container_name: influxdb
    image: influxdb:1.8
    restart: always
    ports:
      - 8086:8086
    networks:
      - iot
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_HTTP_AUTH_ENABLED=true

  chronograf:
    container_name: chronograf
    image: chronograf:1.8
    restart: always
    ports:
      - 8888:8888
    networks:
      - iot
    volumes:
      - chronograf_data:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
networks:
  iot:

volumes:
  mosquitto_data:
  mosquitto_log:
  influxdb_data:
  grafana_data:
  chronograf_data:
